name: api tests
on:
  workflow_dispatch:

env:
  SPOTIFY_CLIENT_ID: ${{vars.SPOTIFY_CLIENT_ID}}
  SPOTIFY_CLIENT_SECRET: ${{secrets.SPOTIFY_CLIENT_SECRET}}
  REFRESH_TOKEN: ${{secrets.REFRESH_TOKEN}}
  REDIRECT_URL: ${{vars.REDIRECT_URL}}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test --project=spotify
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
